### PR TITLE
Tradie management

### PR DESCRIPTION
**Pull request by Fumicode01**
## Rationale

UI feature for Tradie to create a new account, Login and Update profile details

## Advice for Reviewers & Testing Notes

- Explain how your change should be reviewed, and where reviewers should direct their attention.
- Explain (where relevant) how your change can be tested.
Add TradieProfileForm for edit their profile after login
Delete some Unnecessary Code
Fix Fields for  Post requsets to DB

## Screenshots:
Screen Shot 2021-06-16 at 6 33 25 pm (2)

Screen Shot 2021-06-16 at 6 33 25 pm

Screen Shot 2021-06-16 at 6 39 13 pm (2)
Screen Shot 2021-06-16 at 6 39 13 pm
Screen Shot 2021-06-16 at 6 59 51 pm

- Add a screenshot or two of your changes, where applicable.

## Task Name

- Issue Title
Tradie management

## Linting Checklist
- [ ] No commented code
- [ ] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

### CODE REVIEW

**Review by kimchirice — CHANGES_REQUESTED** [review]
suggestions, 

- [mandatory] provide details in PR comments.  saw you left them untouched. it might be easy for you to reason the changes at the time of submission,  but would take more brain power for reviewers to follow the idea. Also consider the situation if you need to come back to your own code after 4-6 weeks.   

-  [mandatory] could you fix the compile warnings with your changes? leave them if they are not related to your changes. 
below are the warning when running "npm start" at my end, FYI.
````cli
Compiled with warnings.

src/App.js
  Line 5:8:  'NewInventory' is defined but never used  no-unused-vars

src/components/Forms/CustomerLogIn.js
  Line 58:47:  'errors' is assigned a value but never used  no-unused-vars

src/components/Forms/CustomerProfileForm.js
  Line 1:16:    'useState' is defined but never used    no-unused-vars
  Line 1:26:    'useEffect' is defined but never used   no-unused-vars
  Line 5:8:     'Link' is defined but never used        no-unused-vars
  Line 8:8:     'Typography' is defined but never used  no-unused-vars
  Line 199:19:  No duplicate props allowed              react/jsx-no-duplicate-props

src/components/Forms/CustomerSignUp.js
  Line 151:17:  No duplicate props allowed  react/jsx-no-duplicate-props
  Line 186:17:  No duplicate props allowed  react/jsx-no-duplicate-props
  Line 245:17:  No duplicate props allowed  react/jsx-no-duplicate-props

src/components/Forms/TradieLogin.js
  Line 64:47:  'errors' is assigned a value but never used  no-unused-vars

src/components/Forms/TradieProfileForm.js
  Line 1:16:    'useState' is defined but never used   no-unused-vars
  Line 1:26:    'useEffect' is defined but never used  no-unused-vars
  Line 192:19:  No duplicate props allowed             react/jsx-no-duplicate-props
  Line 208:17:  No duplicate props allowed             react/jsx-no-duplicate-props

src/components/Forms/TradieSignUp.js
  Line 156:17:  No duplicate props allowed  react/jsx-no-duplicate-props
  Line 191:17:  No duplicate props allowed  react/jsx-no-duplicate-props
  Line 248:17:  No duplicate props allowed  react/jsx-no-duplicate-props

src/components/Forms/useForm.js
  Line 2:8:  'validate' is defined but never used  no-unused-vars

src/components/inventory/NewInventory.js
  Line 1:17:  'useState' is defined but never used          no-unused-vars
  Line 4:8:   'Typography' is defined but never used        no-unused-vars
  Line 5:8:   'TextareaAutosize' is defined but never used  no-unused-vars

src/index.js
  Line 5:25:  'Route' is defined but never used         no-unused-vars
  Line 5:32:  'Switch' is defined but never used        no-unused-vars
  Line 6:8:   'NewInventory' is defined but never used  no-unused-vars
  Line 7:8:   'TradieLogin' is defined but never used   no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
````

3.  [optional] consider remove input fields of.  
  - confirm email
  - confirm password

**Comment by kimchirice** [comment]
hi @Fumicode01 could you help to update the status of this PR, are you working on the new changes or new features??

**Comment by Fumicode01** [comment]
Hi, Max,

I will quickly fix warnings then make PR with comments.
I am sorry for late replying for it.

**Comment by Fumicode01** [comment]
#Add Tradie Login Function     3d1a896

Screen Shot 2021-07-24 at 10 16 41 pm


I changed function name from loginCustomer to loginTradiePerson, created new folder for handling Token and UserData( but, I think this is not right way to do it.)
Screen Shot 2021-07-24 at 10 21 39 pm

**Comment by Fumicode01** [comment]
There are 3 new commits for each functions for Tradie.
- LogIn function for tradie.
- SignUp function for tradie.
- Update profile function for tradie.
Screen Shot 2021-07-29 at 5 43 33 pm
Screen Shot 2021-07-29 at 5 43 43 pm

**Review by kimchirice — CHANGES_REQUESTED** [review]
1. could you seperate the functions related to the customer into another PR. better focus on the tradeperson management in this one. Also it would be easy for the reviewer to review and test your code.

note: I recall we discuss the customer signUp and login not include in the MVP. I might need to double check and confirm this with team. 

2.  remove unncessary comments, especial commentted code. for isntance, when I reun the_'npm start'_ , it compiled with warning
```bash
Compiled with warnings.

src/components/Forms/useForm.js
  Line 38:12:  'loginTradePerson' is assigned a value but never used   no-unused-vars
  Line 54:11:  'signUpTradePerson' is assigned a value but never used  no-unused-vars
```

3. consder tidy up the below section in the Conversation tab, a few suggestions

- think from reviewers point of view. 
```
Advice for Reviewers & Testing Notes
 - Explain how your change should be reviewed, and where reviewers should direct their attention.
 - Explain (where relevant) how your change can be tested.
```
- remove unnecssary screenshots. maybe record a clip/s of how the brower behave of signup, login and update fuction.

4.  resolve the conflicts between this feature brand and main. current it says, 
```markdown
### Conflicting files
- package-lock.json
- src/App.js
- src/components/Forms/SignUp.js
- src/components/Forms/TradieLogin.js
- src/components/Forms/useForm.js
- src/components/rightSideBar/RightSideBar.js
- src/index.js
```  

5. suspect a bug. it appears the email address value is not correct. attach a screenshot
bug_tasksTech

**Review by ettienekorayyi — CHANGES_REQUESTED** [review]
1.At your trader's action, in my opinion, field validation should be on the component level state.
2.Could you put your traderReducer to the rootReducer.js

**Review by ettienekorayyi — CHANGES_REQUESTED** [review]
You can add your newly created reducers in the rootReducer .js instead of putting it in the index.js inside the store directory

**Comment by Fumicode01** [comment]
## Rationale

[Add] Redux on Traders' functions.

I am so sorry about late and huge changes.
But, codes of functions are very similar with previous requests. 
The main differences are changing codes to Redux.

## Advice for Reviewers & Testing Notes
[rem] Remove all unnecessary previous file such as useForm, validateInfo.

[mod] Change name of folder from Form to Trader.
[mod] Modify and Add some codes in actions, reducers, Auth.js

[add] Add code Redux Code for Trader Management such as action.js, actionTypes.js, TraderActions,  reducers/traderReducer.js, selector/userSelector.js
[add] Add some modules that need for Trader Management 

For Testing
Please do "npm install" before start testing to install new modules.
Now, you can try from signup, login and update profile for Trader in each pages.

Also, you can try logout function from Left and Right sidebar.

In addition, if you are not login yet, when you try to open tradie/profile and create/job pages, automatically jump back to login pages because of authentication.

Currently, my code is using localstorage to store Token and ID.



## Screenshots:
Screen Shot 2021-08-15 at 6 46 47 pm
Screen Shot 2021-08-15 at 6 48 15 pm
Screen Shot 2021-08-15 at 6 50 09 pm



## Task Name

Tradie-Management


## Linting Checklist
- [ ] No commented code
- [ ] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

**Review by ettienekorayyi — CHANGES_REQUESTED** [review]
You can pass the traderSignUpData  object in the signUp function instead of properties to make your code a few lines shorter.
// example:
export const signUp = (firstname, lastname,  email, password, confirmPassword, description, phone) => {
    ...
}

export const signUp = (traderSignUpData) => {
    return async (dispatch) =>{
          try {
              taskstechApi.post('users/tradesperson', traderSignUpData)
            .then(res =>{
                console.log(res)
                dispatch(push('/login'))
            })
        } catch(error){
            console.log(error.message)
        }
                 
    }
}

**Comment by Fumicode01** [comment]
> You can pass the traderSignUpData object in the signUp function instead of properties to make your code a few lines shorter.
> // example:
> export const signUp = (firstname, lastname, email, password, confirmPassword, description, phone) => {
> ...
> }
> 
> export const signUp = (traderSignUpData) => {
> return async (dispatch) =>{
> try {
> taskstechApi.post('users/tradesperson', traderSignUpData)
> .then(res =>{
> console.log(res)
> dispatch(push('/login'))
> })
> } catch(error){
> console.log(error.message)
> }
> 
> ```
> }
> ```
> 
> }

Thank you, Stephen!

When I make other pull request after Trader-Authentication, I will change it!

**Pull request merged**
